### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by anthonyle-ql** [os-fpga/Raptor#1471]
Hi, 

Follow the instructions to build Raptor and got error:
###########################
RAPTOR_RECURSIVE_SUBSYTEMS
###########################
Updating tests/Jira_Testcase submodule...
Submodule 'tests/Jira_Testcase' (https://github.com/os-fpga/Jira_Testcase.git) registered for path 'tests/Jira_Testcase'
Cloning into '/home/ale/anthony/test-raptor/Raptor/tests/Jira_Testcase'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/os-fpga/Jira_Testcase.git' into submodule path '/home/ale/anthony/test-raptor/Raptor/tests/Jira_Testcase' failed
Failed to clone 'tests/Jira_Testcase'. Retry scheduled
Cloning into '/home/ale/anthony/test-raptor/Raptor/tests/Jira_Testcase'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/os-fpga/Jira_Testcase.git' into submodule path '/home/ale/anthony/test-raptor/Raptor/tests/Jira_Testcase' failed
Failed to clone 'tests/Jira_Testcase' a second time, aborting
CMake Error at CMakeLists.txt:94 (message):
  "/bin/git submodule update --init --recursive tests/Jira_Testcase" failed
  with 1, please checkout submodule manually
Call Stack (most recent call first):
  CMakeLists.txt:100 (checkout_subsystems)

-- Configuring incomplete, errors occurred!
See also "/home/ale/anthony/test-raptor/Raptor/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:46: run-cmake-release] Error 1

**Comment by alaindargelas** [comment]
Please try again, this is fixed.
