### ISSUE TITLE
Build errorL Qt6 package not found

### ISSUE THREAD

**Issue by anthonyle-ql** [os-fpga/Raptor#1478]
I have installed qt6-base-dev package on Ubuntu 22.04 LTS machine. When execute 'make', I got the error below. I did not make any modifications to any of the checkout files or Qt6 config files. The error is:

-- Found WrapOpenGL: TRUE  
-- Could NOT find XKB (missing: XKB_LIBRARY XKB_INCLUDE_DIR) (Required is at least version "0.5.0")
-- Found WrapVulkanHeaders: /usr/include  
-- Could NOT find Qt6WebEngineWidgets (missing: Qt6WebEngineWidgets_DIR)
-- Could NOT find Qt6WebChannel (missing: Qt6WebChannel_DIR)
CMake Error at FOEDAG_rs/FOEDAG/cmake/cmake_qt.txt:22 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "WebEngineWidgets".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6WebEngineWidgets/Qt6WebEngineWidgetsConfig.cmake"
  does NOT exist

  Failed to find Qt component "WebChannel".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6WebChannel/Qt6WebChannelConfig.cmake"
  does NOT exist

  

Call Stack (most recent call first):
  FOEDAG_rs/FOEDAG/CMakeLists.txt:76 (include)

-- Configuring incomplete, errors occurred!
See also "/home/qlblue/anthony/Raptor/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:46: run-cmake-release] Error 1

**Comment by alaindargelas** [comment]
You are missing a lot of packages:
https://github.com/os-fpga/Raptor/blob/main/.github/workflows/install_ubuntu_dependencies_build.sh
