### ISSUE TITLE
Unable to locate Qt6 packages

### ISSUE THREAD

**Issue by MarkoMk** [os-fpga/Raptor#1699]
- I have been trying to install Raptor on Ubuntu 20.04 and have been following the [install_ubuntu_dependencies_build.sh](https://github.com/os-fpga/Raptor/blob/main/.github/workflows/install_ubuntu_dependencies_build.sh). Whenever it gets to the following packages, I get a message that it can't locate them. The packages are: qt6-webengine-dev, qt6-webengine* & libqt6webenginecore6* (see picture bellow). Would you mind tellig me what I am doing wrong? Thank you in advance.

![image](https://github.com/os-fpga/Raptor/assets/46170875/8a00b795-bd18-42d9-b00f-27e782cff25c)

**Comment by alaindargelas** [comment]
@MarkoMk , please migrate to Ubuntu 22.04 or later.
We don't support 20.04 or 21.04 anymore.

**Comment by MarkoMk** [comment]
Thank you for the swift answer. Sorry for taking up your time!
