### ISSUE TITLE
Raptor crash case with Pin Planner

### ISSUE THREAD

**Issue by w0lek** [os-fpga/Raptor#1867]
The problem was found during the experimenting, if Pin Planner pick up newly added port from HDL.

Steps to reproduce:

- create or open example project and2_gemini
- check Tools/Pin Planner, the two new tabs: "IO Ports" and "Package Pins" are shown
- open and2.v file in editor, and add new port input, for example add

`input a_; `
inside the module and2

was

```
module and2 (
  input a,
  input b,
  input clk,
  input reset,
  output reg c = 1'b0
);

```

become

```
module and2 (
  input a,
  input a_,
  input b,
  input clk,
  input reset,
  output reg c = 1'b0
);
```
- save and2.v in editor
- **uncheck the Tools/Pin Planner action, the Raptor will be crashed here.**
- when we re-open Raptor again, and activate Tools/Pin Planner, it will pick up the new a_ port symbol.

**Comment by ravikiranchollangi** [comment]
@volodymyrkochyn FYI

**Comment by volodymyrkochyn** [comment]
I can reproduce this with just open and close Pin Planner steps

**Comment by volodymyrkochyn** [comment]
Fix here: https://github.com/os-fpga/FOEDAG/pull/1654

**Comment by volodymyrkochyn** [comment]
@w0lek This is done. Please verify the issue.
